creating a numpy array

In [1]:
import numpy as np
arr = np.arange(6)
print(arr.dtype)


int32


checking data type

In [2]:
arr = np.array([1.0, 2.0])
print(arr.dtype == np.float64)


True


creating complex array

In [3]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


converting to float32

In [4]:
arr = np.array([1, 2, 3])
arr = arr.astype(np.float32)
print(arr)


[1. 2. 3.]


reducing precision to float32

In [5]:
arr = np.array([1.0, 2.0], dtype=np.float64)
arr = arr.astype(np.float32)
print(arr)


[1. 2.]


getting array attributes

In [6]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype


getting array dimension

In [7]:
def array_dimension(arr):
    return arr.ndim


item size and total size

In [8]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes


array strides

In [9]:
def array_strides(arr):
    return arr.strides


shape and stride relationship

In [10]:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides


creating zeros array

In [11]:
def create_zeros_array(n):
    return np.zeros(n)


creating ones matrix

In [12]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))


creating range array

In [13]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)


creating linear space

In [14]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)


creating identity matrix

In [15]:
def create_identity_matrix(n):
    return np.eye(n)


converting list to array

In [16]:
def list_to_numpy_array(lst):
    return np.array(lst)


concatenating arrays along axis

In [17]:
def concatenate_arrays(a, b, axis=0):
    return np.concatenate((a, b), axis=axis)

# Example
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(a, b, axis=0))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


horizontally concatenating arrays with different shapes

In [18]:
a = np.array([[1], [2]])
b = np.array([[3, 4], [5, 6]])
b_trimmed = b[:, :1]  # Adjust shape for concatenation
result = np.concatenate((a, b_trimmed), axis=1)
print(result)


[[1 3]
 [2 5]]


vertically stacking multiple arrays

In [19]:
def vertical_stack(arr_list):
    return np.vstack(arr_list)

# Example
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
print(vertical_stack([a, b, c]))


[[1 2]
 [3 4]
 [5 6]]


generating array within range using step

In [20]:
def generate_range(start, stop, step):
    return np.arange(start, stop + 1, step)

print(generate_range(1, 10, 2))


[1 3 5 7 9]


generating equally spaced values

In [21]:
equally_spaced = np.linspace(0, 1, 10)
print(equally_spaced)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


generating logarithmic values

In [22]:
log_space = np.logspace(0, 3, 5)
print(log_space)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


creating dataframe from numpy array

In [23]:
import pandas as pd
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=["A", "B", "C"])
print(df)


    A   B   C
0  39  66  98
1  11  29  31
2  88  12   6
3  29  86  47
4  46  78  66


replacing negative values in column

In [24]:
def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

# Example
df = pd.DataFrame({"A": [-10, 20, -30, 40]})
print(replace_negatives(df, "A"))


    A
0   0
1  20
2   0
3  40


accessing the third element

In [25]:
arr = np.array([10, 20, 30, 40])
print(arr[2])


30


retrieving element from 2d array

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2])


6


extracting elements greater than 5

In [27]:
arr = np.array([1, 6, 8, 2])
print(arr[arr > 5])


[6 8]


slicing from index 2 to 5

In [28]:
arr = np.array([0, 1, 2, 3, 4, 5, 6])
print(arr[2:6])


[2 3 4 5]


slicing sub-array

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[[0, 1], 1:3])


[[2 3]
 [5 6]]


extracting using index array

In [30]:
arr = np.array([[10, 20], [30, 40]])
indices = [0, 1]
print(arr[indices])


[[10 20]
 [30 40]]


filtering with boolean condition

In [31]:
arr = np.array([5, 10, 15, 20])
print(arr[arr > 10])


[15 20]


extracting from 3d using index arrays

In [32]:
arr = np.arange(27).reshape(3, 3, 3)
print(arr[[0, 1], [1, 2], [2, 0]])


[ 5 15]


extracting with two conditions

In [33]:
arr = np.array([10, 15, 20, 25])
print(arr[(arr > 10) & (arr < 25)])


[15 20]


extracting using row and col index

In [34]:
arr = np.array([[1, 2], [3, 4]])
rows = np.array([0, 1])
cols = np.array([1, 0])
print(arr[rows, cols])


[2 3]


adding scalar to array

In [35]:
arr = np.array([1, 2, 3])
print(arr + 5)


[6 7 8]


multiplying row-wise with broadcast

In [36]:
a = np.random.rand(3, 4)
b = np.random.rand(1, 4)
print(a * b)


[[0.30227595 0.05898859 0.10406271 0.85189091]
 [0.08654522 0.74537481 0.05887815 0.09273128]
 [0.35396063 0.81536898 0.10570992 0.90872804]]


adding row vector to 2d array

In [37]:
a = np.random.rand(4, 3)
b = np.random.rand(1, 3)
print(a + b)


[[1.40485577 1.75419813 1.28340665]
 [1.63766685 1.3341868  0.77923293]
 [1.50054227 1.46266626 1.42735106]
 [1.4428238  0.99227164 1.38401482]]


adding (3,1) and (1,3)

In [38]:
a = np.random.rand(3, 1)
b = np.random.rand(1, 3)
print(a + b)


[[1.44973753 1.616272   1.18396172]
 [1.35762825 1.52416272 1.09185245]
 [1.03467995 1.20121442 0.76890414]]


handling shape incompatibility

In [39]:
a = np.random.rand(2, 3)
b = np.random.rand(2, 2)
try:
    result = a * b
except ValueError as e:
    print("Shape mismatch:", e)


Shape mismatch: operands could not be broadcast together with shapes (2,3) (2,2) 


calculating column mean

In [40]:
arr = np.random.rand(3, 4)
print(np.mean(arr, axis=0))


[0.47007468 0.35248307 0.4597633  0.10515736]


finding max in each row

In [41]:
print(np.max(arr, axis=1))


[0.72945814 0.53180724 0.74978531]


finding index of max in columns

In [42]:
print(np.argmax(arr, axis=0))


[0 0 2 1]


applying moving sum

In [43]:
def moving_sum(arr, window=2):
    return np.convolve(arr, np.ones(window, dtype=int), 'valid')

arr = np.array([1, 2, 3, 4, 5])
print(moving_sum(arr))


[3 5 7 9]


checking if all in column are even

In [44]:
arr = np.array([[2, 4], [6, 8]])
print(np.all(arr % 2 == 0, axis=0))


[ True  True]


reshaping array

In [45]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print(reshaped)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


flattening array

In [46]:
print(reshaped.flatten())


[ 0  1  2  3  4  5  6  7  8  9 10 11]


concatenating arrays

In [47]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.concatenate((a, b), axis=0))


[[1 2]
 [3 4]]


splitting array

In [48]:
arr = np.arange(12).reshape(4, 3)
print(np.split(arr, 2, axis=0))


[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]


inserting and deleting elements

In [49]:
arr = np.array([1, 2, 3, 4, 5])
arr = np.insert(arr, 2, 99)
arr = np.delete(arr, 4)
print(arr)


[ 1  2 99  3  5]


element-wise addition

In [50]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)


[5 7 9]


element-wise subtraction

In [51]:
print(a - b)


[-3 -3 -3]


element-wise multiplication

In [52]:
print(a * b)


[ 4 10 18]


element-wise division

In [53]:
print(a / b)


[0.25 0.4  0.5 ]


element-wise power

In [54]:
print(a ** b)


[  1  32 729]


counting substring

In [55]:
arr = np.array(["hello", "world", "hello world"])
print(np.char.count(arr, "lo"))


[1 0 1]


extracting uppercase

In [56]:
arr = np.array(["hello", "world", "hello world"])
print(np.char.count(arr, "lo"))


[1 0 1]


replacing substring

In [57]:
print(np.char.replace(arr, "Hello", "Hi"))


['hello' 'world' 'hello world']


concatenating strings

In [58]:
print(np.char.add(arr, "_suffix"))


['hello_suffix' 'world_suffix' 'hello world_suffix']


finding longest string

In [59]:
print(max(map(len, arr)))


11


mean, median, std, var

In [60]:
data = np.random.randint(1, 1001, 100)
print(np.mean(data), np.median(data), np.var(data), np.std(data))


465.21 455.5 75997.12589999998 275.6757622642948


percentiles

In [61]:
data = np.random.randint(1, 101, 50)
print(np.percentile(data, 25), np.percentile(data, 75))


20.25 71.0


correlation coefficient

In [62]:
x = np.random.rand(10)
y = np.random.rand(10)
print(np.corrcoef(x, y))


[[ 1.         -0.29739233]
 [-0.29739233  1.        ]]


matrix multiplication

In [63]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print(np.dot(a, b))


[[ 4  4]
 [10  8]]


multiple percentiles

In [64]:
data = np.random.randint(1, 101, 50)
print(np.percentile(data, [10, 50, 90]))


[18.  44.5 85. ]


finding index

In [65]:
arr = np.array([10, 20, 30])
print(np.where(arr == 20))


(array([1], dtype=int64),)


sorting array

In [66]:
arr = np.random.randint(1, 100, 10)
print(np.sort(arr))


[ 1  3 12 16 33 39 40 41 92 98]


filtering > 20

In [67]:
print(arr[arr > 20])


[98 39 92 41 40 33]


filtering divisible by 3

In [68]:
print(arr[arr % 3 == 0])


[39  3 33 12]


filtering between 20 and 40

In [69]:
print(arr[(arr >= 20) & (arr <= 40)])


[39 40 33]


checking byte order

In [70]:
arr = np.array([1, 2, 3])
print(arr.dtype.byteorder)


=


performing byte swap

In [71]:
arr = np.array([1, 256, 1024], dtype='>i2')  # big-endian
arr.byteswap(inplace=True)
print(arr)


[256   1   4]
